version: '3.8'

services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sdc
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      # - ./sdc_dump.sql:/docker-entrypoint-initdb.d/sdc_dump.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  cache:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  # load_balancer:
  #   image: nginx:1.25.0-alpine
  #   volumes:
  #     - ./conf.d/default.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 80:4000

  backend:
    image: 127.0.0.1:5000/sdc
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      - EXTERNAL_PORT=3000
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGDATABASE=sdc
      - PGHOST=db
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  db:
    driver: local
  cache:
    driver: local
  load_balancer:
    driver: local