services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sdc
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      # - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # - ./data_set:/tmp/data_set

  cache:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  backend:
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      - EXTERNAL_PORT=3000
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGDATABASE=sdc
      - PGHOST=db
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 80:3000

volumes:
  db:
    driver: local
  cache:
    driver: local