services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sdc
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./data_set:/tmp/data_set

  backend:
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      - EXTERNAL_PORT=3000
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGDATABASE=sdc
      - PGHOST=db
    ports:
      - 3000:3000

volumes:
  db:
    driver: local